title: Lab Notes
author: Josh Hornsby
description: >
  I do stuff that happens.
url: "https://jdhornsby.com"

permalink: /:title/

theme: minima
minima:
  skin: classic
  date_format: "%Y-%m-%d"

show_excerpts: true

future: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - "*.json"
